services:
  starry-cloud:
    container_name: starry-cloud
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - GUNICORN_WORKERS=1
      - GUNICORN_THREADS=2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro